wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/base_experiment/ippo_ff.py
    python_version: 3.9.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709682434.0
    t:
      1:
      - 1
      - 12
      - 41
      - 45
      - 50
      - 55
      2:
      - 1
      - 12
      - 41
      - 45
      - 50
      - 55
      3:
      - 15
      - 23
      4: 3.9.18
      5: 0.16.4
      8:
      - 4
      - 5
      13: darwin-arm64
