"LR_SPEAKER": 1e-4
"LR_LISTENER": 4e-3
"NUM_ENVS": 1
"NUM_STEPS": 256 # 256
"UPDATE_EPOCHS": 4000
"MINIBATCH_SIZE_LISTENER": 64 # 64 # This must be a whole divisor of NUM_STEPS
"MINIBATCH_SIZE_SPEAKER": 64 # 64  # This must be a whole divisor of NUM_STEPS
"GAMMA": 0.0
"GAE_LAMBDA": 0.0
"CLIP_EPS": 0.02
"ENT_COEF_LISTENER": 0.04
"ENT_COEF_SPEAKER": 0.004
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ANNEAL_LR_SPEAKER": False
"ANNEAL_LR_SPEAKER_MULTIPLIER": 1.0
"ANNEAL_LR_LISTENER": False
"ANNEAL_LR_LISTENER_MULTIPLIER": 4.0
"SPEAKER_DROPOUT": 0.0
"LISTENER_DROPOUT": 0.3

"ENV_NAME": "simple-sig-game"
"ENV_DATASET": 'mnist'
"ENV_LISTENER_ARCH": 'convsmall'
"ENV_SPEAKER_ARCH": 'gausssplatchol'
"ENV_NUM_DATAPOINTS": 5000
"ENV_KWARGS":
  "num_speakers": 5
  "num_listeners": 5
  "num_channels": 5
  "num_classes": 10
  "image_dim": 28
  "reward_success": 1.0
  "reward_failure": -0.1
  "channel_ratio_fn": "all_speakers"
  "speaker_action_transform": "gausssplatchol"
  "speaker_action_dim": 30


# WandB Params
"WANDB_MODE": "online"
"ENTITY": "signification-team"
"PROJECT": "signification-game"
"SPEAKER_EXAMPLE_LOGGING_ITER": 50
