"GAMMA": 0.0
"GAE_LAMBDA": 0.0
"CLIP_EPS": 0.02
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ENT_COEF_LISTENER": 0.02  # 0.02 is good for dense, 0.015 is good for conv
"ENT_COEF_SPEAKER": 1e-2
"L2_REG_COEF_LISTENER": 1e-3 # These are subject to change after the bugfix
"L2_REG_COEF_SPEAKER": 5e-4 # These are subject to change after the bugfix
"ACTOR_COEF_LISTENER": 1.0
"OPTIMIZER_SPEAKER_B1": 0.9
"OPTIMIZER_SPEAKER_B2": 0.999
"OPTIMIZER_LISTENER_B1": 0.9
"OPTIMIZER_LISTENER_B2": 0.999


"SPEAKER_LR_SCHEDULE": "1e-4"
"LISTENER_LR_SCHEDULE": "1e-4" #"1e-4 jump to 1e-6 at 300"# 2e-4 is good for conv, 1e-3 is good for dense
"SPEAKER_TRAIN_SCHEDULE": "on" # "off then on at 300"
"LISTENER_TRAIN_SCHEDULE": "on"

"LISTENER_OPTIMIZER": "adam"

"PRETRAINED_LISTENERS": "" #"agents-cifar100-53e-5000dp-fd4e" #"agents-cifar10-600e-3000dp-84e5"
"RESET_LISTENER_OPTIMIZER_COUNTS": True # Probably always keep this True
"PRETRAINED_SPEAKERS": "" #"agents-cifar10-600e-3000dp-84e5"

"LISTENER_ARCH": 'conv'
"SPEAKER_ARCH": 'splines'
"SPEAKER_LATENT_DIM": 128
"SPEAKER_DROPOUT": 0.0
"LISTENER_DROPOUT": 0.0
"SPEAKER_SQUISH": 0.4
"SPEAKER_STDDEV": 0.7
"SPEAKER_STDDEV2": 0.4

"SPEAKER_NOISE_LATENT_DIM": 10
"SPEAKER_NOISE_LATENT_STDDEV": 0.05

"LISTENER_N_SAMPLES": 5
"SPEAKER_N_SEARCH": 7
"MAX_SPEAKER_N_SEARCH": 10
"LISTENER_PR_WEIGHT": 1.0
"SPEAKER_ACTION_SELECTION_BETA": 1.0

"NUM_ENVS": 1  # Always 1
"NUM_STEPS": 2048 # 2048
"UPDATE_EPOCHS": 4000
"MINIBATCH_SIZE_LISTENER": 32 # 32 # This must be a whole divisor of NUM_STEPS
"MINIBATCH_SIZE_SPEAKER": 128 # 128 # This must be a whole divisor of NUM_STEPS

"PROBE_MODEL_NAME": "probe-cifar10-5k-20k-40e-sgd-75f8" # for cifar10 # "probe-5k-20k-20e-sgd-bedc" # for mnist
"PROBE_NUM_EXAMPLES": 512 # 500 # This must be less than or equal to "NUM_STEPS"
"PROBE_MODEL": "cnn"
"PROBE_OPTIMIZER": "adam"

"ENV_NAME": "simple-sig-game"
"ENV_DATASET": 'cifar10b'
"ENV_NUM_DATAPOINTS": 5000
"ENV_KWARGS":
  "num_speakers": 10  # best to have num_speakers = num_listeners
  "num_listeners": 10
  "num_channels": 10
  "num_classes": 10
  "image_dim": 32 # 28 for MNIST, 32 for CIFAR-10
  "speaker_reward_success": 1.0
  "speaker_reward_failure": -0.1
  "listener_reward_success": 1.0
  "listener_reward_failure": -0.1
  "speaker_action_transform": "splines_weight"
  "speaker_action_dim": 21  # This must be a multiple of 6 for "splines"
  "log_prob_rewards": True
  "speaker_whitesum_penalty_coef": 0.0
  "speaker_curve_penalty_coef": 0.0
  "speaker_right_angle_penalty_coef": 0.0
  "speaker_right_angle_or_straight_penalty_coef": 0.0
  "speaker_similar_curve_penalty_coef": 0.0
  "center_and_reshuffle_listener_obs": False
  "gaussian_noise_stddev": 0.05
  "speaker_assignment_method": "arange" # "arange" or "random"
  "reward_parity_fn": "coop"  # "1.0 at 300", "coop", "manip"
  "agent_inferential_mode_fn": "1.0" # Default is "gut" or 0.0, same as lr schedule syntax e.g. "0.23 anneal to 1.0 at 10"
  "channel_ratio_fn": 0.7  # E.g. "1.0 at 300", "sigmoid-custom"
  "speaker_referent_span_fn": 10 # default should be the same as num_classes above
  "mandate_unitary_channel_map": True
  "sigmoid_offset": 600
  "sigmoid_stretch": 5e-3
  "sigmoid_height": 1.0
  "sigmoid_stilt": 0.0

# WandB Params
"WANDB_MODE": "disabled"
"ENTITY": "signification-team"
"PROJECT": "signification-game"
"SPEAKER_EXAMPLE_LOGGING_ITER": 5
"SPEAKER_EXAMPLE_NUM": 2
"SPEAKER_EXAMPLE_DEBUG": False
"LOG_TOM_SPEAKER_EXAMPLES": False
"PROBE_LOGGING_ITER": 1
"WANDB_NOTES": ""

"DEBUGGER": False
"PICKLE_FINAL_AGENTS": False
"JAX_RANDOM_SEED": 50
