"GAMMA": 0.0
"GAE_LAMBDA": 0.0
"CLIP_EPS": 0.02
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ENT_COEF_LISTENER": 0.02  # 0.02 is good for dense, 0.015 is good for conv
"ENT_COEF_SPEAKER": 1e-2
"L2_REG_COEF_LISTENER": 1e-5
"L2_REG_COEF_SPEAKER": 1e-5
"OPTIMIZER_SPEAKER_B1": 0.9
"OPTIMIZER_SPEAKER_B2": 0.999
"OPTIMIZER_LISTENER_B1": 0.9
"OPTIMIZER_LISTENER_B2": 0.999

"SPEAKER_LR_SCHEDULE": "1e-4"
"LISTENER_LR_SCHEDULE": "1e-4 jump to 1e-6 at 300" # 2e-4 is good for conv, 1e-3 is good for dense
"SPEAKER_TRAIN_SCHEDULE": "off then on at 300"
"LISTENER_TRAIN_SCHEDULE": "on"

"LISTENER_ARCH": 'conv'
"SPEAKER_ARCH": 'splines'
"SPEAKER_LATENT_DIM": 128
"SPEAKER_DROPOUT": 0.0
"LISTENER_DROPOUT": 0.0
"SPEAKER_SQUISH": 0.4
"SPEAKER_STDDEV": 0.7
"SPEAKER_STDDEV2": 0.4

"SPEAKER_NOISE_LATENT_DIM": 10
"SPEAKER_NOISE_LATENT_STDDEV": 0.05

"NUM_ENVS": 1
"NUM_STEPS": 10 # 2048
"UPDATE_EPOCHS": 4000
"MINIBATCH_SIZE_LISTENER": 10 # 32 # This must be a whole divisor of NUM_STEPS
"MINIBATCH_SIZE_SPEAKER": 10 # 128 # This must be a whole divisor of NUM_STEPS

"PROBE_MODEL_NAME": "probe-5k-20k-20e-sgd-bedc"
"PROBE_NUM_EXAMPLES": 10 # 500 # This must be less than or equal to "NUM_STEPS"

"ENV_NAME": "simple-sig-game"
"ENV_DATASET": 'mnist'
"ENV_DATASET_CATEGORIES": ["Capsicum", "Pumpkin", "Potato", "Bean", "Cauliflower", "Tomato", "Carrot", "Cabbage", "Broccoli", "Radish"]
"ENV_NUM_DATAPOINTS": 5000
"ENV_KWARGS":
  "num_speakers": 5
  "num_listeners": 5
  "num_channels": 5
  "num_classes": 10
  "image_dim": 28
  "speaker_reward_success": 1.0
  "speaker_reward_failure": -0.1
  "listener_reward_success": 1.0
  "listener_reward_failure": -0.1
  "speaker_action_transform": "splines"
  "speaker_action_dim": 12  # This must be a multiple of 6 for "splines"
  "log_prob_rewards": True
  "speaker_whitesum_penalty_coef": 0.0
  "speaker_curve_penalty_coef": 0.0
  "center_listener_obs": True
  "gaussian_noise_stddev": 0.05
  "speaker_assignment_method": "arange" # "arange" or "random"
  "reward_parity_fn": "1.0 at 300"
  "agent_inferential_mode_fn": "tom" # Default is "gut", "tom at 300"
  "channel_ratio_fn": "0.4"  # E.g. "1.0 at 300", "sigmoid-custom"
  "speaker_referent_span_fn": 10 # default should be the same as num_classes above
  "mandate_unitary_channel_map": False
  "sigmoid_offset": 600
  "sigmoid_stretch": 5e-3
  "sigmoid_height": 1.0


# WandB Params
"WANDB_MODE": "disabled"
"ENTITY": "signification-team"
"PROJECT": "signification-game"
"SPEAKER_EXAMPLE_LOGGING_ITER": 5
"SPEAKER_EXAMPLE_NUM": 2
"SPEAKER_EXAMPLE_DEBUG": False
"PROBE_LOGGING_ITER": 1
"WANDB_NOTES": "Trying an abbreviated speaker introduction timeline."

"DEBUGGER": False
"PICKLE_FINAL_AGENTS": False
"JAX_RANDOM_SEED": 50
