"LR_SPEAKER": 1e-4
"LR_LISTENER": 9e-4   # 2e-4 is good for conv, 9e-4 is good for dense
"GAMMA": 0.0
"GAE_LAMBDA": 0.0
"CLIP_EPS": 0.02
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ENT_COEF_LISTENER": 0.02  # 0.02 is good for dense, 0.015 is good for conv
"ENT_COEF_SPEAKER": 1e-2

"ANNEAL_LR_SPEAKER": False
"ANNEAL_LR_SPEAKER_MULTIPLIER": 1.0
"ANNEAL_LR_LISTENER": False
"ANNEAL_LR_LISTENER_MULTIPLIER": 1.0
"SPEAKER_TRAIN_FREEZE": "on at 200"
"LISTENER_TRAIN_FREEZE": "off at 200"

"LISTENER_ARCH": 'dense'
"SPEAKER_ARCH": 'splines'
"SPEAKER_LATENT_DIM": 200
"SPEAKER_DROPOUT": 0.0
"LISTENER_DROPOUT": 0.0
"SPEAKER_STDDEV": 0.6
"SPEAKER_STDDEV2": 0.3
"SPEAKER_SQUISH": 0.25
"SPEAKER_NOISE_LATENT_DIM": 10
"SPEAKER_NOISE_LATENT_STDDEV": 0.05

"NUM_ENVS": 1
"NUM_STEPS": 2048 # 2048
"UPDATE_EPOCHS": 1500
"MINIBATCH_SIZE_LISTENER": 32 # 32 This must be a whole divisor of NUM_STEPS
"MINIBATCH_SIZE_SPEAKER": 128 # 128  # This must be a whole divisor of NUM_STEPS


"ENV_NAME": "simple-sig-game"
"ENV_DATASET": 'mnist'
"ENV_NUM_DATAPOINTS": 5000
"ENV_KWARGS":
  "num_speakers": 1
  "num_listeners": 10
  "num_channels": 10
  "num_classes": 10
  "image_dim": 28
  "reward_success": 1.0
  "reward_failure": -0.1
  "channel_ratio_fn": "0.1 at 200"
  "speaker_action_transform": "splines"
  "speaker_action_dim": 18


# WandB Params
"WANDB_MODE": "online"
"ENTITY": "signification-team"
"PROJECT": "signification-game"
"SPEAKER_EXAMPLE_LOGGING_ITER": 10
"SPEAKER_EXAMPLE_NUM": 5
"SPEAKER_EXAMPLE_DEBUG": False
