"LR_SPEAKER": 1e-4
"LR_LISTENER": 1e-3   # 2e-4 is good for conv, 1e-3 is good for dense
"GAMMA": 0.0
"GAE_LAMBDA": 0.0
"CLIP_EPS": 0.02
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ENT_COEF_LISTENER": 0.02  # 0.02 is good for dense, 0.015 is good for conv
"ENT_COEF_SPEAKER": 1e-2
"OPTIMIZER_SPEAKER_B1": 0.9
"OPTIMIZER_SPEAKER_B2": 0.999
"OPTIMIZER_LISTENER_B1": 0.9
"OPTIMIZER_LISTENER_B2": 0.999

"ANNEAL_LR_SPEAKER": False
"ANNEAL_LR_LISTENER": True
"ANNEAL_LR_SPEAKER_MULTIPLIER": 1.0
"ANNEAL_LR_LISTENER_MULTIPLIER": 0.75
"SPEAKER_TRAIN_SCHEDULE": "off then on at 100"
"LISTENER_TRAIN_SCHEDULE": "on then off at 100"

"LISTENER_ARCH": 'dense'
"SPEAKER_ARCH": 'splines'
"SPEAKER_LATENT_DIM": 128
"SPEAKER_DROPOUT": 0.0
"LISTENER_DROPOUT": 0.0
"SPEAKER_SQUISH": 0.4
"SPEAKER_STDDEV": 0.7
"SPEAKER_STDDEV2": 0.4

"SPEAKER_NOISE_LATENT_DIM": 10
"SPEAKER_NOISE_LATENT_STDDEV": 0.05

"NUM_ENVS": 1
"NUM_STEPS": 2048 # 2048
"UPDATE_EPOCHS": 2000
"MINIBATCH_SIZE_LISTENER": 32 # 32 This must be a whole divisor of NUM_STEPS
"MINIBATCH_SIZE_SPEAKER": 128 # 128  # This must be a whole divisor of NUM_STEPS


"ENV_NAME": "simple-sig-game"
"ENV_DATASET": 'mnist'
"ENV_NUM_DATAPOINTS": 1000
"ENV_KWARGS":
  "num_speakers": 2
  "num_listeners": 5
  "num_channels": 5
  "num_classes": 10
  "image_dim": 28
  "speaker_reward_success": 1.0
  "speaker_reward_failure": -0.1
  "listener_reward_success": 1.0
  "listener_reward_failure": -0.1
  "channel_ratio_fn": "0.2 at 100"
  "speaker_action_transform": "splines"
  "speaker_action_dim": 12
  "log_prob_rewards": False
  "gaussian_noise_stddev": 0.4
  "speaker_assignment_method": "random"


# WandB Params
"WANDB_MODE": "online"
"ENTITY": "signification-team"
"PROJECT": "signification-game"
"SPEAKER_EXAMPLE_LOGGING_ITER": 10
"SPEAKER_EXAMPLE_NUM": 2
"SPEAKER_EXAMPLE_DEBUG": False
