"LR_SPEAKER": 1e-5
"LR_LISTENER": 5e-5
"GAMMA": 0.0
"GAE_LAMBDA": 0.0
"CLIP_EPS": 0.02
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ENT_COEF_LISTENER": 0.04
"ENT_COEF_SPEAKER": 0.01
"ANNEAL_LR_SPEAKER": False
"ANNEAL_LR_SPEAKER_MULTIPLIER": 1.0
"ANNEAL_LR_LISTENER": False
"ANNEAL_LR_LISTENER_MULTIPLIER": 1.0
"SPEAKER_TRAIN_FREEZE": "on_at_300"
"LISTENER_TRAIN_FREEZE": "on_at_300"

"LISTENER_ARCH": 'dense'
"SPEAKER_ARCH": 'gauss_splatchol'
"SPEAKER_LATENT_DIM": 64
"SPEAKER_DROPOUT": 0.0
"LISTENER_DROPOUT": 0.0

"NUM_ENVS": 1
"NUM_STEPS": 30 # 1024
"UPDATE_EPOCHS": 3
"MINIBATCH_SIZE_LISTENER": 5 # 64 # This must be a whole divisor of NUM_STEPS
"MINIBATCH_SIZE_SPEAKER": 5 # 128  # This must be a whole divisor of NUM_STEPS


"ENV_NAME": "simple-sig-game"
"ENV_DATASET": 'mnist'
"ENV_NUM_DATAPOINTS": 5000
"ENV_KWARGS":
  "num_speakers": 1
  "num_listeners": 5
  "num_channels": 5
  "num_classes": 10
  "image_dim": 28
  "reward_success": 1.0
  "reward_failure": -0.1
  "channel_ratio_fn": "20th_at_300"
  "speaker_action_transform": "gauss_splatchol"
  "speaker_action_dim": 60


# WandB Params
"WANDB_MODE": "disabled"
"ENTITY": "signification-team"
"PROJECT": "signification-game"
"SPEAKER_EXAMPLE_LOGGING_ITER": 25
