"LR": 1e-4
"NUM_ENVS": 1
"NUM_STEPS": 128
"UPDATE_EPOCHS": 5000
"MINIBATCH_SIZE": 32  # This must be a whole divisor of NUM_STEPS
"GAMMA": 0.0
"GAE_LAMBDA": 0.0
"CLIP_EPS": 0.02
"ENT_COEF": 0.015
"VF_COEF": 0.8
"MAX_GRAD_NORM": 0.95
"ENV_NAME": "simple-sig-game"
"ENV_DATASET": 'mnist'
"ENV_LISTENER_ARCH": 'conv'
"ENV_NUM_DATAPOINTS": 5
"ENV_KWARGS":
  "num_speakers": 1
  "num_listeners": 1
  "num_channels": 1
  "num_classes": 10
  "image_dim": 28
  "reward_success": 1.0
  "reward_failure": -0.1
"ANNEAL_LR": False

# WandB Params
"WANDB_MODE": "disabled"
"ENTITY": "signification-team"
"PROJECT": "signification-game"
