"LR_SPEAKER": 4e-5
"LR_LISTENER": 4e-3
"NUM_ENVS": 2
"NUM_STEPS": 256 # 256
"UPDATE_EPOCHS": 100
"MINIBATCH_SIZE_LISTENER": 64 # This must be a whole divisor of NUM_STEPS
"MINIBATCH_SIZE_SPEAKER": 64 # 64  # This must be a whole divisor of NUM_STEPS
"GAMMA": 0.0
"GAE_LAMBDA": 0.0
"CLIP_EPS": 0.02
"ENT_COEF_LISTENER": 0.04
"ENT_COEF_SPEAKER": 1.5e-4
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ANNEAL_LR_SPEAKER": False
"ANNEAL_LR_SPEAKER_MULTIPLIER": 1.0
"ANNEAL_LR_LISTENER": True
"ANNEAL_LR_LISTENER_MULTIPLIER": 0.25
"SPEAKER_DROPOUT": 0.0
"LISTENER_DROPOUT": 0.4

"ENV_NAME": "simple-sig-game"
"ENV_DATASET": 'mnist'
"ENV_LISTENER_ARCH": 'convsmall'
"ENV_SPEAKER_ARCH": 'gausssmallnovar'
"ENV_NUM_DATAPOINTS": 2000
"ENV_KWARGS":
  "num_speakers": 2
  "num_listeners": 2
  "num_channels": 2
  "num_classes": 10
  "image_dim": 28
  "reward_success": 1.0
  "reward_failure": -0.1
  "channel_ratio_fn": "all_speakers"


# WandB Params
"WANDB_MODE": "online"
"ENTITY": "signification-team"
"PROJECT": "signification-game"
