"ENV_NUM_DATAPOINTS": 5000
"PROBE_NUM_DATAPOINTS_VALIDATION": 20000
"BATCH_SIZE": 128
"NUM_EPOCHS": 35
"LEARNING_RATE": 0.05
"MOMENTUM": 0.9
"OPTIMIZER": "sgd"

"ENV_DATASET": "cifar10"
"ENV_KWARGS":
  "num_classes": 10
  "image_dim": 32

"TRAIN_MODEL": True
"SAVE_MODEL": False
"EVAL_MODEL": False
"MODEL_NAME_PREFIX": "probe-cifar10-5k-20k-35e-sgd-"
"MODEL_NAME_EVAL": "probe-cifar10-5k-20k-20e-sgd-bedc"


# WandB Params
"WANDB_MODE": "disabled"
"ENTITY": "signification-team"
"PROJECT": "icon-probe"
"WANDB_NOTES": "Training probe for cifar-10"
"DEBUGGER": False
