"ENV_NUM_DATAPOINTS": 5000
"PROBE_NUM_DATAPOINTS_VALIDATION": 1000
"BATCH_SIZE": 32
"NUM_EPOCHS": 50
"LEARNING_RATE": 0.001

# WandB Params
"WANDB_MODE": "online"
"ENTITY": "signification-team"
"PROJECT": "icon-probe"
"WANDB_NOTES": "Initial testing of icon probe training."
