"ENV_NUM_DATAPOINTS": 5000
"PROBE_NUM_DATAPOINTS_VALIDATION": 5000
"BATCH_SIZE": 128
"NUM_EPOCHS": 100
"LEARNING_RATE": 0.05
"MOMENTUM": 0.9


# WandB Params
"WANDB_MODE": "online"
"ENTITY": "signification-team"
"PROJECT": "icon-probe"
"WANDB_NOTES": "Initial testing of icon probe training."
