program: ippo_ff.py
method: bayes
name: listener-sweep-conv
metric:
  goal: maximize
  name: reward/mean reward/all listeners
parameters:
  LR_LISTENER:
    max: 1e-3
    min: 1e-5
    distribution: log_uniform_values
  WANDB_MODE:
    value: online
  UPDATE_EPOCHS:
    value: 250
  NUM_STEPS:
    value: 2048
  LISTENER_LR_SCHEDULE:
    value: False
  ENT_COEF_LISTENER:
    max: 1.0
    min: 1e-3
    distribution: log_uniform_values
  LISTENER_TRAIN_FREEZE:
    value: "always_train"
  SPEAKER_TRAIN_FREEZE:
    value: "always_train"
  MINIBATCH_SIZE_LISTENER:
    values: [32, 64, 128]
  LISTENER_ARCH:
    value: "conv"


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
