program: ippo_ff.py
method: bayes
name: listener-sweep
metric:
  goal: maximize
  name: reward/mean reward/all listeners
parameters:
  LR_LISTENER:
    max: 1e-3
    min: 1e-8
    distribution: log_uniform_values
  WANDB_MODE:
    value: online
  UPDATE_EPOCHS:
    value: 500
  NUM_STEPS:
    value: 512
  ANNEAL_LR_LISTENER:
    value: True
  ANNEAL_LR_LISTENER_MULTIPLIER:
    value: 0.25
  ANNEAL_LR_SPEAKER:
    value: False


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
