program: ippo_ff.py
method: bayes
name: speaker-sweep-cifar-3spline
metric:
  goal: maximize
  name: reward/mean reward/speaker 0
parameters:
  WANDB_MODE:
    value: online
  UPDATE_EPOCHS:
    value: 1500
  NUM_STEPS:
    value: 2048
  SPEAKER_LR_SCHEDULE:
    values: [1e-5, 1e-4, 1e-3]
  ENT_COEF_SPEAKER:
    max: 0.1
    min: 1e-3
    distribution: log_uniform_values
  L2_REG_COEF_SPEAKER:
    max: 1e-3
    min: 1e-6
    distribution: log_uniform_values
  SPEAKER_TRAIN_SCHEDULE:
    value: "off then on at 300"
  LISTENER_TRAIN_SCHEDULE:
    value: "1e-4 jump to 1e-6 at 300"
  MINIBATCH_SIZE_SPEAKER:
    values: [32, 64, 128]
  LISTENER_ARCH:
    value: "conv"
  SPEAKER_EXAMPLE_LOGGING_ITER:
    value: 100


command:
  - ${env}
  - python
  - ${program}
  - +dataset=cifar10
  - ${args_no_hyphens}
