program: ippo_ff.py
method: bayes
name: speaker-sweep-high-ent-more-listeners
metric:
  goal: maximize
  name: reward/mean reward/all speakers
parameters:
  LR_SPEAKER:
    max: 1e-3
    min: 1e-6
    distribution: log_uniform_values
  WANDB_MODE:
    value: online
  ENT_COEF_SPEAKER:
    max: 1e3
    min: 1e-6
    distribution: log_uniform_values


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
