program: ippo_ff.py
method: bayes
name: speaker-sweep-sig
metric:
  goal: maximize
  name: reward/mean reward/all speakers
parameters:
  LR_SPEAKER:
    max: 1e-3
    min: 1e-5
    distribution: log_uniform_values
  WANDB_MODE:
    value: online
  UPDATE_EPOCHS:
    value: 2500
  NUM_STEPS:
    value: 256
  ENT_COEF_SPEAKER:
    max: 0.1
    min: 1e-2
    distribution: log_uniform_values
  ANNEAL_LR_LISTENER:
    value: True
  ANNEAL_LR_LISTENER_MULTIPLIER:
    value: 1.0
  ANNEAL_LR_SPEAKER:
    value: False


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
