program: ippo_ff.py
method: bayes
name: bandit-sweep-fixed
metric:
  goal: maximize
  name: reward/mean reward/listener 0
parameters:
  LR:
    max: 1e-3
    min: 5e-8
    distribution: uniform
  CLIP_EPS:
    max: 0.5
    min: 0.01
    distribution: uniform
  ENT_COEF:
    max: 0.05
    min: 0.01
    distribution: uniform
  VF_COEF:
    max: 1.0
    min: 0.01
    distribution: uniform
  MAX_GRAD_NORM:
    max: 1.0
    min: 0.01
    distribution: uniform
  MINIBATCH_SIZE:
    values: [32, 128]
  ANNEAL_LR:
    values: [True, False]
  ENV_NUM_DATAPOINTS:
    values: [20, 200, 2000]
  WANDB_MODE:
    value: online
  ENV_LISTENER_ARCH:
    values: ["conv", "dense"]
  UPDATE_EPOCHS:
    value: 3000
  NUM_STEPS:
    value: 256


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
