program: ippo_ff.py
method: bayes
metric:
  goal: maximize
  name: average reward for listener 0
parameters:
  LR:
    max: 5e-5
    min: 5e-8
    distribution: uniform
  CLIP_EPS:
    max: 0.5
    min: 0.01
    distribution: uniform
  ENT_COEF:
    max: 0.05
    min: 0.01
    distribution: uniform
  VF_COEF:
    max: 1.0
    min: 0.01
    distribution: uniform
  MAX_GRAD_NORM:
    max: 1.0
    min: 0.01
    distribution: uniform
  MINIBATCH_SIZE:
    values: [32, 64, 128]
  ANNEAL_LR:
    values: [True, False]


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
