program: ippo_ff.py
method: bayes
metric:
  goal: maximize
  name: average reward for listener 0
parameters:
  LR:
    max: 5e-5
    min: 5e-8
    distribution: uniform
  GAMMA:
    values: [0.99, 0.9]
  CLIP_EPS:
    max: 0.5
    min: 0.1
    distribution: uniform
  ENT_COEF:
    max: 0.05
    min: 0.01
    distribution: uniform
  VF_COEF:
    max: 1.0
    min: 0.1
    distribution: uniform
  MAX_GRAD_NORM:
    max: 1.0
    min: 0.1
    distribution: uniform
  GAE_LAMBDA:
    values: [0.9, 0.95, 1.0]
  MINIBATCH_SIZE:
    values: [16, 32, 64]
  ANNEAL_LR:
    values: [True, False]


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
