"LR": 5e-4
"NUM_ENVS": 2
"NUM_STEPS": 64
"TOTAL_TIMESTEPS": 1e6
"UPDATE_EPOCHS": 3
"MINIBATCH_SIZE": 32  # This must be a whole divisor of NUM_STEPS
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ENV_NAME": "simple-sig-game"
"ENV_DATASET": 'mnist'
"ENV_KWARGS": {}
"ANNEAL_LR": False

# WandB Params
"WANDB_MODE": "disabled"
"ENTITY": "signification-team"
"PROJECT": "signification-game"
