# @package _global_
"PROBE_MODEL_NAME": "probe-cifar10-5k-20k-40e-sgd-75f8"
"ENV_DATASET": "cifar10"

"ENT_COEF_LISTENER": 0.07
"ENT_COEF_SPEAKER": 0.01
"L2_REG_COEF_LISTENER": 1.5e-6
"L2_REG_COEF_SPEAKER": 1e-5

"NUM_STEPS": 2048 # 2048
"UPDATE_EPOCHS": 2000
"MINIBATCH_SIZE_LISTENER": 64 # 64 # This must be a whole divisor of NUM_STEPS
"MINIBATCH_SIZE_SPEAKER": 128 # 128 # This must be a whole divisor of NUM_STEPS
"ENV_NUM_DATAPOINTS": 5000

"ENV_KWARGS":
  ${ENV_KWARGS}:
  "image_dim": 32 # 28 for MNIST, 32 for CIFAR-10
